apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
  namespace: pg
data:
  rules.yaml: |-
    apiVersion: 1
    groups:
      - orgId: 1
        name: '{{ .Chart.Name }}_my_rule_group'
        folder: my_first_folder
        interval: 60s
        rules:
          - uid: my_id_1
            title: my_first_rule
            condition: A
            data:
              - refId: A
                datasourceUid: '-100'
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - A
                      reducer:
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: '-100'
                  expression: 1==0
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
                  type: math
            noDataState: Alerting
            for: 60s
            annotations:
              some_key: some_value
            labels:
              team: sre_team_1
          - uid: my_id_2
            title: my_second_rule
            condition: A
            data:
              - refId: A
                datasourceUid: '-100'
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - A
                      reducer:
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: '-100'
                  expression: 1==0
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
                  type: math
            noDataState: Alerting
            for: 60s
            annotations:
              some_key: some_value
            labels:
              team: sre_team_2
      - orgId: 1
        name: '{{ .Chart.Name }}_my_second_rule_group'
        folder: my_second_folder
        interval: 60s
        rules:
          - uid: my_id_3
            title: my_third_rule
            condition: A
            data:
              - refId: A
                datasourceUid: '-100'
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - A
                      reducer:
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: '-100'
                  expression: 1==0
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
                  type: math
            noDataState: Alerting
            for: 60s
            annotations:
              some_key: some_value
            labels:
              team: sre_team_3             
  contactpoints.yaml: |-
      apiVersion: 1
      contactPoints:
          - orgId: 1
            name: cp_1
            receivers:
              - name: cp_1
                uid: my_id_1
                type: slack
                disableResolveMessage: false
                settings:
                  url: https://hooks.slack.com/services/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
                  summary: |
                     {{ `{{ include "default.message" . }}` }}
          - orgId: 1    
            name: cp_2
            receivers:                 
              - name: cp_2
                uid: my_id_2
                type: slack
                disableResolveMessage: false
                settings:
                  url: https://hooks.slack.com/services/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
                  summary: |
                     {{ `{{ include "default.message" . }}` }}