apiVersion: v1
kind: Pod
metadata:
  name: limittest
spec:
  containers:
  - name: proapp
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "300m"
      limits:
        memory: "128Mi"
        cpu: "500m"

