apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
  creationTimestamp: "2023-04-10T11:05:49Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: elasticsearch-master
  name: elasticsearch-master-elasticsearch-master-0
  namespace: elasticsearch
  resourceVersion: "540"
  uid: 5cefad06-c2e9-475b-ad20-2ebb118175a8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: mystandard
  volumeMode: Filesystem
  volumeName: pvc-5cefad06-c2e9-475b-ad20-2ebb118175a8
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  phase: Bound
